export enum TaskStatus {
    TODO = 'TODO',
    IN_PROGRESS = 'IN_PROGRESS',
    DONE = 'DONE'
}

export enum TaskPriority {
    LOW = 'LOW',
    MEDIUM = 'MEDIUM',
    HIGH = 'HIGH'
}

export interface Task {
    id: number,
    title: string,
    description?: string,
    status: TaskStatus,
    priority: TaskPriority,
    createdAt: string
}

/**
 * Input type for creating and updating tasks.
 * Excludes 'id' and 'createdAt' because they are automatically generated by the server
 * and should not be provided or modified by the client.
 */
export type TaskInput = Omit<Task, 'id' | 'createdAt'>;